# Generated by Django 3.0.3 on 2020-04-23 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('mileage', models.IntegerField()),
            ],
        ),
    ]
