# Generated by Django 3.0.3 on 2020-05-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelsupply',
            options={'get_latest_by': 'date'},
        ),
    ]
